coverage:
  ignore:
    - *
    - tests/.*
    - src/external/hauser_parabolic_smoother/.*
    - src/aikido/tests/.*
    - src/aikido/src/external/hauser_parabolic_smoother/.*
    - "src/aikido/tests/.*"
    - "src/aikido/src/external/hauser_parabolic_smoother/.*"
