dist: trusty

sudo: required

language: generic

env:
  global:
    - TIMEOUT=30

cache:
  - apt

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COVERALLS=ON COMPILER=GCC
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release COVERALLS=OFF COMPILER=GCC
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug COVERALLS=OFF COMPILER=CLANG
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release COVERALLS=OFF COMPILER=CLANG
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Debug COVERALLS=OFF COMPILER=CLANG
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Release COVERALLS=OFF COMPILER=CLANG

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then . ci/before_install_linux.sh; fi

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then . ci/install_linux.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx"   ]; then . ci/install_macos.sh; fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then . ci/script_linux.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx"   ]; then . ci/script_macos.sh; fi

after_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then . scripts/view-all-results.sh test_results; fi

after_failure: 
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log
